// Generated by CoffeeScript 1.6.2
var five, generateButton, _;

_ = require('lodash');

five = require('johnny-five');

generateButton = function(pin) {
  return new five.Button({
    pin: pin
  });
};

five.Board().on('ready', function() {
  var button, handlers, injectables, light, lightOn, makeyPins;

  light = new five.Led({
    pin: 14
  });
  button = new five.Button({
    pin: 5
  });
  injectables = {
    light: light,
    button: button
  };
  makeyPins = {
    click: 6,
    space: 7,
    right: 15,
    left: 13,
    down: 8,
    up: 12
  };
  lightOn = false;
  button.on('down', function() {
    return console.log("button down");
  });
  handlers = {
    click: function() {
      console.log('click pressed!');
      if (lightOn) {
        light.off();
        console.log("Light off!");
        return lightOn = false;
      } else {
        light.on();
        console.log("Light on!");
        return lightOn = true;
      }
    },
    space: function() {
      return console.log('space pressed!');
    },
    right: function() {
      return console.log('right pressed!');
    },
    left: function() {
      return console.log('left pressed!');
    },
    up: function() {
      return console.log('up pressed!');
    },
    down: function() {
      return console.log('down pressed!');
    }
  };
  _(makeyPins).keys().each(function(key) {
    var pin;

    pin = makeyPins[key];
    button = generateButton(pin);
    button.on('down', handlers[key]);
    return injectables[key] = button;
  });
  return this.repl.inject(injectables);
});
